### ISSUE TITLE
Provide pre-computed embeddings to FASTopic

### ISSUE THREAD

**Issue by keithcallenberg** [BobXWu/FASTopic#6]
If I have already computed embeddings for my documents, is there a way I can provide those to FASTopic to speed up the processing?

[BERTopic allows this](https://maartengr.github.io/BERTopic/getting_started/tips_and_tricks/tips_and_tricks.html#pre-compute-embeddings) by adding an `embeddings` parameter to the fit_transform() function. 

Would you welcome a PR that added `embeddings` as an optional parameter to [FASTopic's fit_transform](https://github.com/BobXWu/FASTopic/blob/e46b6057f1a915d9e91a701f947afc2842017bd2/fastopic/FASTopic.py#L116)?

**Comment by BobXWu** [comment]
Hi Keith, thank you for your interest in our work!
Please refer to the [Question 4](https://github.com/BobXWu/Fastopic?tab=readme-ov-file#qa). You need to wrap the way you compute embeddings as an embedding model and pass it to FASTopic. FASTopic will use the _encode_ function.

**Comment by keithcallenberg** [comment]
It looks to me like the solution in Question 4 still assumes that the embeddings have not already been computed. 
But maybe I could hack that solution so that it's something like this?
```
class YourDocEmbedModel:
    def __init__(self, embeddings):
        self.embeddings = embeddings

    def encode(self,
            docs: List[str],
            show_progress_bar: bool=False,
            normalize_embeddings: bool=False
        ):
        ...
        return self.embeddings

your_model = YourDocEmbedModel(embeddings=pre_computed_embeddings)
FASTopic(50, doc_embed_model=your_model)
```
Do you see what I mean? Like if I'm getting my embeddings from a vector store.

**Comment by BobXWu** [comment]
Your solution is a good workaround for training FASTopic. But it causes errors during testing, since FASTopic will use the _encode_ function to get the doc embeddings of testing samples.
Thus, your solution is all right if you don't care about the testing.

**Comment by keithcallenberg** [comment]
Thanks for pointing that out. I guess this works for me for now; I'm fine with just using `fit_transform` and not being able to save the model and do downstream `transform` operations.
